#!/usr/bin/env bash

vc $1 -o ${1/.c/}.bin "${@:2}"
qniceconv 0x8000 < ${1/.c/}.bin > ${1/.c/}.out

if [ $OSTP = "LINUX" ]; then
    if hash xclip 2>/dev/null; then
        cat $destination | xclip -selection clipboard
    fi;
elif [ $OSTP = "OSX" ]; then
    cat $destination | pbcopy
fi;
