		; QNICE assembler code generated by lcc
		; Assemble with qasm.

#include "../dist_kit/sysdef.asm"
#include "../dist_kit/monitor.def"

		.ORG	0x8000

main:
		MOVE	 R0, @--R13	; save
		MOVE	 R7, @--R13	; save
;
		XOR	R7, R7
		MOVE	16, R12	; opd -> reg
		RBRA	L5, 1
L2
L3
		MOVE	R12, R11	; LOADU2
		MOVE	R11,R12
		ADD	0x0001, R12
		ADD	R11, R7
L5
		CMPU	33, R12
		RBRA	L2, N
		MOVE	R12, R0	; LOADI2
L1
;
		MOVE	@R13++, R7	; restore
		SYSCALL(exit, 1)

