# AmigaOS 4.x/PPC

TARGET = vlink_os4
DIR = AmigaOS4

CC = vc +aosppc
CCOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
COPTS = -c -O1
CONFIG = -DAMIGAOS -D__USE_INLINE__

LD = vc +aosppc
LDOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
LDOPTS =
LIBS = -lamiga


include make.rules
