# AmigaOS/68k

TARGET = vlink_os3
DIR = AmigaM68k

CC = vc +aos68k
CCOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
COPTS = -c99 -cpu=68020 -c -O1
CONFIG = -DAMIGAOS

LD = vc +aos68k
LDOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
LDOPTS =
LIBS =


include make.rules
