# WarpOS

TARGET = vlink_wos
DIR = WarpOS

CC = vc +warpos
CCOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
COPTS = -c99 -c -O1
CONFIG = -DAMIGAOS

LD = vc +warpos
LDOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
LDOPTS =
LIBS = -lamiga


include make.rules
