# PowerUp

TARGET = vlink_pup
DIR = PowerUp

CC = vc +powerup
CCOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
COPTS = -c99 -c -O1
CONFIG = -DAMIGAOS

LD = vc +powerup
LDOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
LDOPTS =
LIBS = -lamiga


include make.rules
