# MorphOS

TARGET = vlink_mos
DIR = MorphOS

CC = vc +morphos
CCOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
COPTS = -c -O1
CONFIG = -DAMIGAOS

LD = vc +morphos
LDOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
LDOPTS = 
LIBS = -lamiga


include make.rules
